### PR TITLE
[WIP] Fixed small typo in tutorial

### PR DESCRIPTION
**Pull request by cyrilou242**
## Description of proposed changes
"user-define transformation function" --> "user-define**d** transformation function"

## Related issue(s)
N/A

Fixes # (issue)
Typo, no issue

## Test plan
N/A

## Checklist

* [x] I have read the **CONTRIBUTING** document.
* [ ] I have verified that my changes are covered by continuous integration.
* [ ] All new and existing tests passed.

Skipped testing.

### CODE REVIEW

**Comment by cyrilou242** [comment]
Shame on me. I confused snorkel and snorkel-tutorials, and as you could see I had not read the CONTRIBUTING doc.

The test fail is quite strange as it is not linked to my modifications, I'll have a look.
It looks like at some time in the tutorial, 5 or more false positive are expected, but it can happen that there are less than 5, so the sample function of pandas return an error

I used the graphic interface of github to propose this small change, this will of course not allow to follow the contributing guidelines. I'll delete this MR and start from an issue.

Thank you for your patience :)

**Comment by henryre** [comment]
Hi @cyrilou242, sorry for the inconvenience here! Definitely not on you to fix that test, so feel free to reopen this PR. Not sure what's going wrong there since there's been no material change, no updated packages, and this hasn't failed before. But we'll dig on this today. If you've already found something, just let us know. Thanks again!!

**Comment by cyrilou242** [comment]
I could identify the source of the problem (spacy new version) for the tests, I opened a dedicated issue  https://github.com/snorkel-team/snorkel-tutorials/issues/160#issuecomment-538421195

**Comment by vincentschen** [comment]
@cyrilou242 — now that https://github.com/snorkel-team/snorkel-tutorials/issues/160 is addressed (thanks for bringing this up!) looks like tests are just failing on the difference between `.py` (Jupytext percent format) and `.ipynb`.

`tox -e spam -- sync` _should_ do the trick!

Thanks for your patience on this patch! :)

**Pull request closed without merging**
