### PR TITLE
Add set -euxo pipefail to bash scripts

### PR DESCRIPTION
**Pull request by brahmaneya**
Also add checks for current directory, and check existence of each file (except for scene_graph, where we just check the lower level directories because there are too many files). Delete data dir and refresh if any file is missing, otherwise skip download. 

**Test Plan**
Tox passes.

Example error in jupyter (produced by changing the url of the crowdsourcing data to an incorrect one):

Screen Shot 2019-08-07 at 10 50 37 PM

Also tried removing a single file from data/ to check that it correctly refreshes the directory.

### CODE REVIEW

**Comment by brahmaneya** [comment]
Made a couple more changes:
1) Cleanup data/ in case of failure to make the script more robust to errors (earlier, if it failed once, it would still create the data/ directory, which would make it fail silently the second time due to if [ ! -d "data" ]).
2) Changed subprocess call to save stderr and print it in case of error.

**Comment by henryre** [comment]
sgtm! I had proposed checking existence of individual files rather than the data directory (could always be some corruption, etc.). Do you prefer that or the approach you have in now?

**Comment by brahmaneya** [comment]
> sgtm! I had proposed checking existence of individual files rather than the data directory (could always be some corruption, etc.). Do you prefer that or the approach you have in now?

Added checks for individual files (except in scene graph where there are too many files, so just checking for lowest level of directories.

**Comment by brahmaneya** [comment]
Submitting because travis is failing due to an unrelated bug in scene graph.

**Pull request merged**
