### PR TITLE
utils.py file has been updated

### PR DESCRIPTION
**Pull request by abs007**
## Description of proposed changes

Changed the utils.py file so that the load_data() function can be called when implementing the code, locally.

## Related issue(s)

No more errors being thrown when calling the load_data() function.

### CODE REVIEW

**Comment by abs007** [comment]
@rsmith49 I have submitted the pull request. Would love to hear back from you wrt to this pr.

**Comment by rsmith49** [comment]
Hi @abs007! Unfortunately I believe taking this line completely out will cause users to not have the files downloaded at all. Could you instead have `load_data` take an optional flag on whether to download the data via the bash script, and then in the notebook add a few comments to the corresponding cell on how to call `load_data(download_data=False)` if someone runs into trouble with the bash script?

Thank you for taking the time to address this!

**Comment by abs007** [comment]
@rsmith49  Should I then also add documentation to the readme file that states how one can download the data manually if they are unable to do so via the bash script?

**Comment by abs007** [comment]
@rsmith49 could you provide an update?

**Comment by rsmith49** [comment]
Hi @abs007, I am not seeing any change to the `load_data` function like described, or to the README. Were there additional changes that you intended to push?

**Comment by abs007** [comment]
@rsmith49  I have pushed the changes. For some reason spouse_demo.ipynb seems to have a huge number of changes. 
I checked the file in my branch but it seems to be alright. Could you provide some insight into this matter? Thanks.

**Comment by abs007** [comment]
@rsmith49 .

**Comment by abs007** [comment]
@rsmith49  Could you provide an input, thanks

**Pull request closed without merging**
